(() => {
  "use strict";

  const diagnosticPackages = Object.freeze([
    { id: "TechPowerUp.GPU-Z", version: "2.70.0" },
    { id: "CrystalDewWorld.CrystalDiskInfo", version: "9.9.2" },
    { id: "REALiX.HWiNFO", version: "8.50" },
    { id: "OCBase.OCCT.Personal", version: "17.0.16.0" },
    { id: "CPUID.CPU-Z", version: "2.21" },
  ]);

  function normalizeDrive(value) {
    const match = /^([D-Z]):?$/i.exec(String(value || "").trim());
    if (!match) throw new Error("Укажи одну букву флешки от D до Z, например E:");
    return `${match[1].toUpperCase()}:`;
  }

  function buildUsbPrepCommand(value) {
    const drive = normalizeDrive(value);
    const packages = diagnosticPackages
      .map(({ id, version }) => `[pscustomobject]@{Id='${id}';Version='${version}'}`)
      .join(",");
    return [
      "$ErrorActionPreference='Stop'",
      `$Drive='${drive}'`,
      "$Volume=Get-CimInstance Win32_LogicalDisk -Filter (\"DeviceID='\"+$Drive+\"'\")",
      "if(-not $Volume){throw 'Флешка с этой буквой не найдена'}",
      "if([int]$Volume.DriveType -ne 2){throw 'Выбранный диск не помечен Windows как съёмная флешка'}",
      "$WingetCommand=Get-Command winget.exe -ErrorAction SilentlyContinue",
      "if(-not $WingetCommand){throw 'WinGet не найден. Обнови App Installer из Microsoft Store'}",
      "$Winget=[IO.Path]::GetFullPath($WingetCommand.Source)",
      "$ExpectedWingetRoot=[IO.Path]::GetFullPath((Join-Path $env:LOCALAPPDATA 'Microsoft\\WindowsApps')+'\\')",
      "if(-not $Winget.StartsWith($ExpectedWingetRoot,[StringComparison]::OrdinalIgnoreCase)){throw 'WinGet найден вне системного App Installer — запуск отменён'}",
      "$SourceRaw=& $Winget source export --name winget --disable-interactivity",
      "if($LASTEXITCODE -ne 0 -or -not $SourceRaw){throw 'Не удалось проверить источник WinGet'}",
      "$Source=$SourceRaw | ConvertFrom-Json",
      "if($Source.Name -ne 'winget' -or $Source.Arg -ne 'https://cdn.winget.microsoft.com/cache' -or $Source.Identifier -ne 'Microsoft.Winget.Source_8wekyb3d8bbwe' -or $Source.Type -ne 'Microsoft.PreIndexed.Package' -or $Source.TrustLevel -notcontains 'Trusted'){throw 'Источник winget изменён или не является доверенным — запуск отменён'}",
      "$Run=Get-Date -Format 'yyyyMMdd-HHmmss'",
      "$Root=Join-Path ($Drive+'\\') 'PC-Check'",
      "$RunRoot=Join-Path $Root $Run",
      "$Tools=Join-Path $RunRoot 'Tools'",
      "$Staging=Join-Path $RunRoot '.staging'",
      "New-Item -ItemType Directory -Force -Path $Tools,$Staging | Out-Null",
      "try{$null=$null",
      "$SourceRaw | Set-Content -Encoding UTF8 -Path (Join-Path $RunRoot 'WINGET-SOURCE.json')",
      `$Packages=@(${packages})`,
      "$Failed=@()",
      "$ManifestRows=@()",
      "$TaskKill=Join-Path $env:SystemRoot 'System32\\taskkill.exe'",
      "foreach($Package in $Packages){$Id=$Package.Id;$Version=$Package.Version;$Stage=Join-Path $Staging $Id;New-Item -ItemType Directory -Force -Path $Stage|Out-Null;Write-Host ('winget download --id '+$Id+' --version '+$Version+' --exact --source winget --download-directory '+$Stage) -ForegroundColor Cyan;$TimeoutMs=if($Id -eq 'CPUID.CPU-Z'){45000}else{180000};$Psi=New-Object System.Diagnostics.ProcessStartInfo;$Psi.FileName=$Winget;$Psi.Arguments=('download --id '+$Id+' --version '+$Version+' --exact --source winget --download-directory '+$Stage+' --accept-source-agreements --accept-package-agreements --disable-interactivity');$Psi.UseShellExecute=$false;$Process=[System.Diagnostics.Process]::Start($Psi);$Completed=$Process.WaitForExit($TimeoutMs);if(-not $Completed){$KillerExit=$null;try{$KillPsi=New-Object System.Diagnostics.ProcessStartInfo;$KillPsi.FileName=$TaskKill;$KillPsi.Arguments=('/PID '+$Process.Id+' /T /F');$KillPsi.UseShellExecute=$false;$Killer=[System.Diagnostics.Process]::Start($KillPsi);if($Killer.WaitForExit(5000)){$KillerExit=$Killer.ExitCode}else{try{$Killer.Kill();$Killer.WaitForExit(1000)|Out-Null}catch{}}}catch{};$StoppedAfterKill=$Process.WaitForExit(5000);if(-not $StoppedAfterKill -or $KillerExit -ne 0){try{if(-not $Process.HasExited){$Process.Kill()}}catch{};$StoppedAfterKill=$Process.WaitForExit(5000)};$Failed+=($Id+' '+$Version+' (таймаут)');if(-not $StoppedAfterKill){throw 'Процесс загрузки не удалось остановить'};continue};if($Process.ExitCode -ne 0){$Failed+=($Id+' '+$Version+' (exit '+$Process.ExitCode+')');continue};$Payload=@(Get-ChildItem $Stage -Recurse -File -ErrorAction SilentlyContinue);if(-not $Payload.Count){$Failed+=($Id+' '+$Version+' (нет файла)');continue};$PackageDir=Join-Path $Tools $Id;Move-Item -LiteralPath $Stage -Destination $PackageDir;Get-ChildItem $PackageDir -Recurse -File|ForEach-Object{$Hash=Get-FileHash $_.FullName -Algorithm SHA256;$ManifestRows+=[pscustomobject]@{PackageId=$Id;Version=$Version;SourceName=$Source.Name;SourceIdentifier=$Source.Identifier;File=$_.FullName.Substring($Tools.Length).TrimStart('\\');SHA256=$Hash.Hash}}}",
      "$Manifest=Join-Path $RunRoot 'SHA256.csv'",
      "$ManifestRows | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $Manifest",
      "$DefenderOk=$false",
      "try{$ScanStart=Get-Date;Start-MpScan -ScanType CustomScan -ScanPath $Tools -ErrorAction Stop;$Threats=@(Get-MpThreatDetection -ErrorAction Stop|Where-Object{$_.InitialDetectionTime -ge $ScanStart});$IntegrityOk=$true;foreach($Row in $ManifestRows){$VerifiedPath=Join-Path $Tools $Row.File;if(-not (Test-Path -LiteralPath $VerifiedPath -PathType Leaf)){$IntegrityOk=$false;break};$VerifiedHash=(Get-FileHash -LiteralPath $VerifiedPath -Algorithm SHA256 -ErrorAction Stop).Hash;if($VerifiedHash -ne $Row.SHA256){$IntegrityOk=$false;break}};if($Threats.Count){$Failed+='Defender обнаружил угрозу'}elseif(-not $IntegrityOk){$Failed+='После проверки Defender файл удалён или изменён'}else{$DefenderOk=$true}}catch{$Failed+='Проверка Defender или контроль файлов недоступны'}",
      "$Explorer=Join-Path $env:SystemRoot 'explorer.exe'",
      "if($Failed.Count -or -not $DefenderOk){throw 'Не все проверки подготовки пройдены'}",
      "$Readme=@('COMPLETE — PC CHECK','Версии и источник зафиксированы в SHA256.csv и WINGET-SOURCE.json.','Файлы скачаны через доверенный WinGet, его проверка хэшей не отключалась.','Defender завершил CustomScan без новых обнаружений.','Ничего не установлено и не запущено. Не запускай OCCT Power.')",
      "$Readme | Set-Content -Encoding UTF8 -Path (Join-Path $RunRoot 'COMPLETE.txt')",
      "& $Explorer $RunRoot",
      "Write-Host ('Флешка подготовлена: '+$RunRoot) -ForegroundColor Green",
      "}catch{$Reasons=if($Failed.Count){$Failed}else{@('Подготовка прервана до завершения')};@('INCOMPLETE — ФЛЕШКА НЕ ГОТОВА','Не устанавливай и не запускай файлы из этого набора.','Причины:')+$Reasons|Set-Content -Encoding UTF8 -Path (Join-Path $RunRoot 'INCOMPLETE.txt');& (Join-Path $env:SystemRoot 'explorer.exe') $RunRoot;throw 'Подготовка не завершена. Смотри INCOMPLETE.txt'}",
    ].join("; ");
  }

  function buildAutocheckCommand() {
    return [
      "$ErrorActionPreference='Stop'",
      "$Stamp=Get-Date -Format 'yyyyMMdd-HHmmss'",
      "$Root=Join-Path ([Environment]::GetFolderPath('Desktop')) ('PC-Check-'+$Stamp)",
      "New-Item -ItemType Directory -Force -Path $Root | Out-Null",
      "$Cpu=@(Get-CimInstance Win32_Processor | Select-Object Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed)",
      "$Gpu=@(Get-CimInstance Win32_VideoController | Select-Object Name,DriverVersion,AdapterRAM,VideoModeDescription)",
      "$Ram=@(Get-CimInstance Win32_PhysicalMemory | Select-Object Manufacturer,PartNumber,Capacity,Speed,ConfiguredClockSpeed)",
      "$Storage=@(Get-PhysicalDisk | ForEach-Object{$Disk=$_;$Reliability=$null;try{$Reliability=$_ | Get-StorageReliabilityCounter -ErrorAction Stop}catch{};[pscustomobject]@{Name=$Disk.FriendlyName;MediaType=$Disk.MediaType;Health=$Disk.HealthStatus;Operational=($Disk.OperationalStatus -join ',');SizeBytes=$Disk.Size;Temperature=$Reliability.Temperature;Wear=$Reliability.Wear;PowerOnHours=$Reliability.PowerOnHours}})",
      "$DeviceProblems=try{@(Get-PnpDevice -PresentOnly -ErrorAction Stop | Where-Object{$_.Status -ne 'OK'} | Select-Object Class,Status,Problem)}catch{@([pscustomobject]@{Class='UNAVAILABLE';Status='UNAVAILABLE';Problem='UNAVAILABLE'})}",
      "$Whea=@(Get-WinEvent -FilterHashtable @{LogName='System';ProviderName='Microsoft-Windows-WHEA-Logger';StartTime=(Get-Date).AddDays(-30)} -ErrorAction SilentlyContinue | Select-Object TimeCreated,Id,LevelDisplayName)",
      "$Defender=try{Get-MpComputerStatus -ErrorAction Stop | Select-Object AntivirusEnabled,RealTimeProtectionEnabled,AntivirusSignatureLastUpdated}catch{[pscustomobject]@{Status='UNAVAILABLE'}}",
      "$Report=[ordered]@{CollectedAt=(Get-Date).ToString('o');CPU=$Cpu;GPU=$Gpu;RAM=$Ram;Storage=$Storage;DeviceProblems=$DeviceProblems;WheaLast30Days=$Whea;Defender=$Defender;Limits=@('GPU AdapterRAM из WMI может быть неточным — сверь в GPU-Z','Блок питания и физическое состояние программно не проверяются','Нагрузочные тесты этим этапом не запускаются')} ",
      "$Json=Join-Path $Root 'report.json'",
      "$Report | ConvertTo-Json -Depth 7 | Set-Content -Encoding UTF8 -Path $Json",
      "$CpuNames=($Cpu | ForEach-Object{$_.Name}) -join ', ' ",
      "$GpuNames=($Gpu | ForEach-Object{$_.Name}) -join ', ' ",
      "$RamGb=[math]::Round((($Ram | Measure-Object Capacity -Sum).Sum/1GB),1)",
      "$DiskLines=($Storage | ForEach-Object{$_.Name+' / '+$_.Health}) -join '; ' ",
      "$Lines=@('АВТОЭТАП ЗАВЕРШЁН',('CPU: '+$CpuNames),('GPU: '+$GpuNames),('RAM: '+$RamGb+' ГБ'),('Диски: '+$DiskLines),('Проблемные устройства: '+$DeviceProblems.Count),('WHEA за 30 дней: '+$Whea.Count),'','НЕ ПРОВЕРЕНО: БП, корпус, порты, точная VRAM и стабильность под нагрузкой.','Не оплачивай ПК до ручного осмотра и контролируемого теста.')",
      "$Text=Join-Path $Root 'СНАЧАЛА-ПРОЧТИ.txt'",
      "$Lines | Set-Content -Encoding UTF8 -Path $Text",
      "& (Join-Path $env:SystemRoot 'System32\\notepad.exe') $Text",
      "Write-Host ('Отчёт сохранён: '+$Root) -ForegroundColor Green",
    ].join("; ");
  }

  function buildGuidedSessionCommand() {
    const packages = diagnosticPackages
      .map(({ id, version }) => `[pscustomobject]@{Id='${id}';Version='${version}'}`)
      .join(",");
    return [
      "$ErrorActionPreference='Stop'",
      "$SafeMode=($env:PC_CHECK_SAFE_MODE -eq '1')",
      "$Stamp=Get-Date -Format 'yyyyMMdd-HHmmss'",
      "$Root=Join-Path ([Environment]::GetFolderPath('Desktop')) ('PC-Check-Guided-'+$Stamp)",
      "New-Item -ItemType Directory -Force -Path $Root | Out-Null",
      "$Incomplete=Join-Path $Root 'INCOMPLETE.txt'",
      "@('INCOMPLETE — РУЧНЫЕ ТЕСТЫ ЕЩЁ НЕ ПОДТВЕРЖДЕНЫ','Автоматический этап не является итогом проверки.')|Set-Content -Encoding UTF8 -Path $Incomplete",
      "try{$null=$null",
      "$WingetCommand=Get-Command winget.exe -ErrorAction SilentlyContinue",
      "if(-not $WingetCommand){throw 'WinGet не найден. Обнови App Installer из Microsoft Store'}",
      "$Winget=[IO.Path]::GetFullPath($WingetCommand.Source)",
      "$LocalAppData=[Environment]::GetFolderPath('LocalApplicationData')",
      "$ExpectedWinget=[IO.Path]::GetFullPath((Join-Path $LocalAppData 'Microsoft\\WindowsApps\\winget.exe'))",
      "if(-not [string]::Equals($Winget,$ExpectedWinget,[StringComparison]::OrdinalIgnoreCase)){throw 'WinGet найден вне системного App Installer — запуск отменён'}",
      "$AppInstaller=Get-AppxPackage -Name Microsoft.DesktopAppInstaller -ErrorAction Stop|Select-Object -First 1",
      "if(-not $AppInstaller -or $AppInstaller.PublisherId -ne '8wekyb3d8bbwe' -or $AppInstaller.Publisher -notlike 'CN=Microsoft Corporation,*' -or [string]$AppInstaller.SignatureKind -ne 'Store' -or [string]$AppInstaller.Status -ne 'Ok'){throw 'Подлинность Microsoft App Installer не подтверждена — запуск отменён'}",
      "$SourceRaw=& $Winget source export --name winget --disable-interactivity",
      "if($LASTEXITCODE -ne 0 -or -not $SourceRaw){throw 'Не удалось проверить источник WinGet'}",
      "$Source=$SourceRaw|ConvertFrom-Json",
      "if($Source.Name -ne 'winget' -or $Source.Arg -ne 'https://cdn.winget.microsoft.com/cache' -or $Source.Identifier -ne 'Microsoft.Winget.Source_8wekyb3d8bbwe' -or $Source.Type -ne 'Microsoft.PreIndexed.Package' -or $Source.TrustLevel -notcontains 'Trusted'){throw 'Источник winget изменён или не является доверенным — запуск отменён'}",
      "$SourceRaw|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'WINGET-SOURCE.json')",
      "$SessionStart=Get-Date",
      "$Providers='Microsoft-Windows-WHEA-Logger','Microsoft-Windows-Kernel-Power','Microsoft-Windows-WER-SystemErrorReporting','Display','disk','stornvme','storahci'",
      "function Get-RelevantEvents([datetime]$Start){try{return @(Get-WinEvent -FilterHashtable @{LogName='System';StartTime=$Start} -ErrorAction Stop|Where-Object{$Providers -contains $_.ProviderName}|Select-Object TimeCreated,ProviderName,Id,LevelDisplayName)}catch{if($_.FullyQualifiedErrorId -like 'NoMatchingEventsFound*'){return @()};throw}}",
      "function Get-StorageSnapshot(){return @(Get-PhysicalDisk -ErrorAction Stop|ForEach-Object{$Disk=$_;$Reliability=$null;$ReliabilityStatus='AVAILABLE';try{$Reliability=$_|Get-StorageReliabilityCounter -ErrorAction Stop}catch{$ReliabilityStatus='UNAVAILABLE'};[pscustomobject]@{DeviceId=$Disk.DeviceId;FriendlyName=$Disk.FriendlyName;MediaType=[string]$Disk.MediaType;HealthStatus=[string]$Disk.HealthStatus;OperationalStatus=([string[]]$Disk.OperationalStatus -join ',');Size=$Disk.Size;ReliabilityStatus=$ReliabilityStatus;Temperature=$Reliability.Temperature;Wear=$Reliability.Wear;PowerOnHours=$Reliability.PowerOnHours;ReadErrorsUncorrected=$Reliability.ReadErrorsUncorrected;WriteErrorsUncorrected=$Reliability.WriteErrorsUncorrected}})}",
      "$Baseline=@(Get-RelevantEvents ($SessionStart.AddDays(-30)))",
      "ConvertTo-Json -InputObject $Baseline -Depth 4|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'events-baseline.json')",
      "$StorageBefore=@(Get-StorageSnapshot)",
      "ConvertTo-Json -InputObject $StorageBefore -Depth 5|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'storage-baseline.json')",
      `$PackagePlans=@(${packages})`,
      "$InstallLog=@()",
      "$Unavailable=@()",
      "$TaskKill=Join-Path $env:SystemRoot 'System32\\taskkill.exe'",
      "function Get-InstalledPackageVersions([string]$Path){& $Winget export --output $Path --include-versions --accept-source-agreements --disable-interactivity|Out-Null;if($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $Path -PathType Leaf)){throw 'Не удалось получить версии установленных WinGet-пакетов'};$Export=Get-Content -LiteralPath $Path -Raw|ConvertFrom-Json;return @($Export.Sources|ForEach-Object{$_.Packages})}",
      "$InstalledBeforePath=Join-Path $Root 'installed-before.json'",
      "$InstalledBefore=@(Get-InstalledPackageVersions $InstalledBeforePath)",
      "foreach($Package in $PackagePlans){$Id=$Package.Id;$Version=$Package.Version;$Existing=$InstalledBefore|Where-Object{$_.PackageIdentifier -ceq $Id}|Select-Object -First 1;if($Existing -and $Existing.Version -ceq $Version){$InstallLog+=($Id+' '+$Version+' already exact');continue};Write-Host ('winget install --id '+$Id+' --version '+$Version+' --exact --source winget') -ForegroundColor Cyan;$TimeoutMs=if($Id -eq 'CPUID.CPU-Z'){30000}else{300000};$Psi=New-Object System.Diagnostics.ProcessStartInfo;$Psi.FileName=$Winget;$Psi.Arguments=('install --id '+$Id+' --version '+$Version+' --exact --source winget --silent --accept-source-agreements --accept-package-agreements --disable-interactivity');$Psi.UseShellExecute=$false;$Process=[System.Diagnostics.Process]::Start($Psi);$Completed=$Process.WaitForExit($TimeoutMs);if(-not $Completed){$KillerExit=$null;try{$KillPsi=New-Object System.Diagnostics.ProcessStartInfo;$KillPsi.FileName=$TaskKill;$KillPsi.Arguments=('/PID '+$Process.Id+' /T /F');$KillPsi.UseShellExecute=$false;$Killer=[System.Diagnostics.Process]::Start($KillPsi);if($Killer.WaitForExit(5000)){$KillerExit=$Killer.ExitCode}else{try{$Killer.Kill();$Killer.WaitForExit(1000)|Out-Null}catch{}}}catch{};$StoppedAfterKill=$Process.WaitForExit(5000);if(-not $StoppedAfterKill -or $KillerExit -ne 0){try{if(-not $Process.HasExited){$Process.Kill()}}catch{};$StoppedAfterKill=$Process.WaitForExit(5000)};if(-not $StoppedAfterKill){throw ('Процесс WinGet не удалось остановить: '+$Id)};if($Id -eq 'CPUID.CPU-Z'){$Unavailable+=$Id;continue};throw ('Таймаут WinGet: '+$Id)};if($Process.ExitCode -ne 0){if($Id -eq 'CPUID.CPU-Z'){$Unavailable+=$Id;continue};throw ('WinGet не установил '+$Id+' '+$Version+'; exit '+$Process.ExitCode)};$InstallLog+=($Id+' '+$Version+' installed')}",
      "$InstalledAfterPath=Join-Path $Root 'installed-after.json'",
      "$InstalledAfter=@(Get-InstalledPackageVersions $InstalledAfterPath)",
      "foreach($Package in $PackagePlans){if($Unavailable -contains $Package.Id){continue};$VerifiedPackage=$InstalledAfter|Where-Object{$_.PackageIdentifier -ceq $Package.Id}|Select-Object -First 1;if(-not $VerifiedPackage -or $VerifiedPackage.Version -cne $Package.Version){throw ('Версия WinGet-пакета не подтверждена: '+$Package.Id+' '+$Package.Version)}}",
      "$InstallLog|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'installed-tools.txt')",
      "$ProgramFiles=[Environment]::GetFolderPath('ProgramFiles')",
      "$ProgramFilesX86=[Environment]::GetFolderPath('ProgramFilesX86')",
      "$PackagesRoot=Join-Path $LocalAppData 'Microsoft\\WinGet\\Packages'",
      "function Find-Tool([string[]]$AllowedPaths,[string]$PackageDirectory,[string[]]$Names,[string]$Label){foreach($Candidate in $AllowedPaths){if($Candidate -and (Test-Path -LiteralPath $Candidate -PathType Leaf)){return [IO.Path]::GetFullPath($Candidate)}};if($PackageDirectory){$ExactPackagePath=Join-Path $PackagesRoot $PackageDirectory;if(Test-Path -LiteralPath $ExactPackagePath -PathType Container){$Found=Get-ChildItem $ExactPackagePath -Recurse -File -ErrorAction Stop|Where-Object{$Names -ccontains $_.Name}|Select-Object -First 1;if($Found){return $Found.FullName}}};throw ('Не найден файл точного WinGet-пакета: '+$Label)}",
      "function Confirm-Tool([string]$Path,[string]$ExpectedPublisher,[string]$ExpectedVersion){$Signature=Get-AuthenticodeSignature -LiteralPath $Path -ErrorAction Stop;$Publisher=if($Signature.SignerCertificate){$Signature.SignerCertificate.GetNameInfo([Security.Cryptography.X509Certificates.X509NameType]::SimpleName,$false)}else{''};if([string]$Signature.Status -ne 'Valid' -or $Publisher -cne $ExpectedPublisher){throw ('Недоверенная подпись или издатель: '+$Path)};if($ExpectedVersion){$ActualVersion=(Get-Item -LiteralPath $Path).VersionInfo.FileVersion;if(-not $ActualVersion -or -not $ActualVersion.StartsWith($ExpectedVersion,[StringComparison]::Ordinal)){throw ('Неожиданная версия '+$ExpectedVersion+': '+$Path)}}}",
      "$CpuZ=$null;if($Unavailable -notcontains 'CPUID.CPU-Z'){$CpuZ=Find-Tool @((Join-Path $ProgramFiles 'CPUID\\CPU-Z\\cpuz.exe'),(Join-Path $ProgramFiles 'CPUID\\CPU-Z\\cpuz_x64.exe')) '' @('cpuz.exe','cpuz_x64.exe') 'CPUID.CPU-Z'}",
      "$GpuZ=Find-Tool @((Join-Path $ProgramFilesX86 'GPU-Z\\GPU-Z.exe')) '' @('GPU-Z.exe') 'TechPowerUp.GPU-Z'",
      "$CrystalDiskInfo=Find-Tool @((Join-Path $ProgramFiles 'CrystalDiskInfo\\DiskInfo64.exe'),(Join-Path $ProgramFiles 'CrystalDiskInfo\\DiskInfo32.exe')) '' @('DiskInfo64.exe','DiskInfo32.exe') 'CrystalDewWorld.CrystalDiskInfo'",
      "$Hwinfo=Find-Tool @((Join-Path $ProgramFiles 'HWiNFO64\\HWiNFO64.exe')) '' @('HWiNFO64.exe') 'REALiX.HWiNFO'",
      "$Occt=Find-Tool @() 'OCBase.OCCT.Personal_Microsoft.Winget.Source_8wekyb3d8bbwe' @('OCCT.exe') 'OCBase.OCCT.Personal'",
      "if($CpuZ){Confirm-Tool $CpuZ 'CPUID' '2.21'}",
      "Confirm-Tool $GpuZ 'TechPowerUp LLC' '2.70.0'",
      "Confirm-Tool $CrystalDiskInfo 'CrystalMark Inc.' '9.9.2'",
      "Confirm-Tool $Hwinfo 'REALiX, s.r.o.' '8.50'",
      "Confirm-Tool $Occt 'OCBASE' ''",
      "$CpuReportBase=Join-Path $Root 'CPU-Z-report'",
      "if($CpuZ){$CpuProcess=Start-Process -FilePath $CpuZ -ArgumentList ('-txt='+$CpuReportBase) -PassThru;if(-not $CpuProcess.WaitForExit(60000)){$CpuStopped=$false;try{if(-not $CpuProcess.HasExited){$CpuProcess.Kill()};$CpuStopped=$CpuProcess.WaitForExit(5000)}catch{};if(-not $CpuStopped){throw 'CPU-Z завис и не был остановлен'};throw 'CPU-Z не завершил автоматический отчёт'};if(-not (Test-Path -LiteralPath ($CpuReportBase+'.txt') -PathType Leaf)){throw 'CPU-Z не создал свежий отчёт'}}else{@('CPU-Z недоступен с этой сети. Не ищи случайное зеркало.','Открой HWiNFO Summary и сверь CPU, плату и RAM вручную.','До этой сверки CPU/RAM остаются НЕ ПРОВЕРЕНО.')|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'CPU-Z-НЕДОСТУПЕН.txt')}",
      "$DiskProcess=Start-Process -FilePath $CrystalDiskInfo -ArgumentList '/CopyExit' -PassThru",
      "if(-not $DiskProcess.WaitForExit(60000)){$DiskStopped=$false;try{if(-not $DiskProcess.HasExited){$DiskProcess.Kill()};$DiskStopped=$DiskProcess.WaitForExit(5000)}catch{};if(-not $DiskStopped){throw 'CrystalDiskInfo завис и не был остановлен'};throw 'CrystalDiskInfo не завершил /CopyExit'}",
      "$DiskText=Join-Path (Split-Path $CrystalDiskInfo) 'DiskInfo.txt'",
      "if((Test-Path -LiteralPath $DiskText -PathType Leaf) -and (Get-Item -LiteralPath $DiskText).LastWriteTime -ge $SessionStart){Copy-Item -LiteralPath $DiskText -Destination (Join-Path $Root 'CrystalDiskInfo.txt') -Force}else{throw 'CrystalDiskInfo не создал свежий DiskInfo.txt'}",
      "$Plan=@('PC CHECK — РУЧНОЙ ЭТАП ОБЯЗАТЕЛЕН','Этот бесплатный сценарий не управляет интерфейсом OCCT Personal.','On-site Screen 25–30 минут: сверка железа и SMART; CPU-only 3 мин; CPU+RAM Large 2 мин; Memory 3 мин; 3D Adaptive Variable 15–100% 5 мин; VRAM/Render Test 2 мин; порты и системные события. Это быстрый отсев перед оплатой, не гарантия полной стабильности.','Home Screen 90–120 минут после покупки: смотри точный профиль на сайте; не оставляй тесты без наблюдения.','Maximum 8–12+ часов: смотри точный профиль на сайте; MemTest86 требует перезагрузки.','Power не запускается автоматически.','После тестов закрой OCCT и вернись в Терминал. Нажми Enter только когда ручные результаты и скриншоты сохранены.')",
      "$PlanPath=Join-Path $Root 'СНАЧАЛА-ПРОЧТИ.txt'",
      "$Plan|Set-Content -Encoding UTF8 -Path $PlanPath",
      "if(-not $SafeMode){Start-Process -FilePath (Join-Path $env:SystemRoot 'System32\\notepad.exe') -ArgumentList $PlanPath;Start-Process -FilePath $GpuZ|Out-Null;Start-Process -FilePath $Hwinfo|Out-Null;$OcctProcess=Start-Process -FilePath $Occt -PassThru;Read-Host 'После завершения ручных тестов и сохранения доказательств нажми Enter'|Out-Null}else{'SAFE MODE: интерфейсы и нагрузка не запускались'|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'SAFE-MODE.txt')}",
      "$Post=@(Get-RelevantEvents $SessionStart)",
      "ConvertTo-Json -InputObject $Post -Depth 4|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'events-during-session.json')",
      "$CriticalPost=@($Post|Where-Object{($_.ProviderName -eq 'Microsoft-Windows-WHEA-Logger') -or ($_.ProviderName -eq 'Microsoft-Windows-Kernel-Power' -and $_.Id -eq 41) -or ($_.ProviderName -eq 'Microsoft-Windows-WER-SystemErrorReporting' -and $_.Id -eq 1001) -or ($_.ProviderName -eq 'Display' -and $_.Id -eq 4101) -or ($_.ProviderName -in @('disk','stornvme','storahci') -and $_.LevelDisplayName -in @('Critical','Error','Warning'))})",
      "if($CriticalPost.Count){@('STOP — НОВЫЕ КРИТИЧНЫЕ СИСТЕМНЫЕ СОБЫТИЯ',('Количество: '+$CriticalPost.Count),'Смотри events-during-session.json')|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'STOP-SYSTEM-EVENTS.txt')}",
      "$PostDiskStart=Get-Date",
      "$PostDiskProcess=Start-Process -FilePath $CrystalDiskInfo -ArgumentList '/CopyExit' -PassThru",
      "if(-not $PostDiskProcess.WaitForExit(60000)){$PostDiskStopped=$false;try{if(-not $PostDiskProcess.HasExited){$PostDiskProcess.Kill()};$PostDiskStopped=$PostDiskProcess.WaitForExit(5000)}catch{};if(-not $PostDiskStopped){throw 'CrystalDiskInfo post-check завис и не был остановлен'};throw 'CrystalDiskInfo не завершил повторный /CopyExit'}",
      "if((Test-Path -LiteralPath $DiskText -PathType Leaf) -and (Get-Item -LiteralPath $DiskText).LastWriteTime -ge $PostDiskStart){Copy-Item -LiteralPath $DiskText -Destination (Join-Path $Root 'CrystalDiskInfo-post.txt') -Force}else{throw 'CrystalDiskInfo не создал свежий post-check'}",
      "$StorageAfter=@(Get-StorageSnapshot)",
      "ConvertTo-Json -InputObject $StorageAfter -Depth 5|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'storage-post.json')",
      "$StorageFlags=@($StorageAfter|Where-Object{$_.HealthStatus -ne 'Healthy' -or $_.OperationalStatus -notmatch 'OK' -or ($null -ne $_.ReadErrorsUncorrected -and $_.ReadErrorsUncorrected -gt 0) -or ($null -ne $_.WriteErrorsUncorrected -and $_.WriteErrorsUncorrected -gt 0)})",
      "$MissingDisks=@($StorageBefore|Where-Object{$BeforeId=$_.DeviceId;$StorageAfter.DeviceId -notcontains $BeforeId})",
      "if($StorageFlags.Count -or $MissingDisks.Count){@('STOP — POST-CHECK НАКОПИТЕЛЕЙ ТРЕБУЕТ ПРОВЕРКИ',('Количество флагов: '+$StorageFlags.Count),('Исчезнувшие диски: '+$MissingDisks.Count),'Смотри storage-post.json и CrystalDiskInfo-post.txt')|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'STOP-STORAGE.txt')}",
      "$Inventory=[ordered]@{CollectedAt=(Get-Date).ToString('o');CPU=@(Get-CimInstance Win32_Processor|Select-Object Name,NumberOfCores,NumberOfLogicalProcessors);GPU=@(Get-CimInstance Win32_VideoController|Select-Object Name,DriverVersion);RAM=@(Get-CimInstance Win32_PhysicalMemory|Select-Object Manufacturer,PartNumber,Capacity,Speed,ConfiguredClockSpeed);Storage=@(Get-PhysicalDisk|Select-Object FriendlyName,MediaType,HealthStatus,OperationalStatus,Size)}",
      "$Inventory|ConvertTo-Json -Depth 6|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'inventory-post.json')",
      "@('АВТОМАТИЧЕСКИЙ СБОР ЗАВЕРШЁН','INCOMPLETE сохраняется, пока человек не подтвердит каждый тест на сайте.','Новые релевантные события: '+$Post.Count,'Критичные новые события: '+$CriticalPost.Count,'Флаги post-check накопителей: '+$StorageFlags.Count,'Исчезнувшие диски: '+$MissingDisks.Count,'Папка доказательств: '+$Root)|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'АВТОСБОР-ЗАВЕРШЁН.txt')",
      "Start-Process -FilePath (Join-Path $env:SystemRoot 'explorer.exe') -ArgumentList $Root",
      "}catch{$Reason=$_.Exception.Message;@('INCOMPLETE — АВТОМАТИЧЕСКИЙ ЭТАП ПРЕРВАН','Причина: '+$Reason,'Не считай этот ПК проверенным.')|Set-Content -Encoding UTF8 -Path $Incomplete;@((Get-Date).ToString('o'),$Reason)|Set-Content -Encoding UTF8 -Path (Join-Path $Root 'ERROR.txt');Start-Process -FilePath (Join-Path $env:SystemRoot 'explorer.exe') -ArgumentList $Root;throw}",
    ].join("; ");
  }

  window.PcCheckCommands = Object.freeze({
    buildUsbPrepCommand,
    buildAutocheckCommand,
    buildGuidedSessionCommand,
  });
})();
