<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>PC-Check</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PcCheck.Core/PcCheck.Core.csproj" />
  </ItemGroup>
</Project>
